[package]
name = "bls-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["use_wasm_bindgen"]
use_wasm_bindgen = []

[dependencies]
reqwest = { version = "0.11.20", default-features = false }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
